(() => {
  'use strict';
  const enc=new TextEncoder();
  const ascii=s=>enc.encode(String(s));
  const MM=72/25.4;
  const PAGE_SIZES={A4:{w:210,h:297},Carta:{w:216,h:279},Ofício:{w:216,h:356}};
  function concat(chunks){let n=0;for(const c of chunks)n+=c.length;const out=new Uint8Array(n);let o=0;for(const c of chunks){out.set(c,o);o+=c.length;}return out;}
  function latinByte(ch){const code=ch.charCodeAt(0);if(code<=255)return code;const map={'€':128,'‚':130,'ƒ':131,'„':132,'…':133,'†':134,'‡':135,'ˆ':136,'‰':137,'Š':138,'‹':139,'Œ':140,'Ž':142,'‘':145,'’':146,'“':147,'”':148,'•':149,'–':150,'—':151,'˜':152,'™':153,'š':154,'›':155,'œ':156,'ž':158,'Ÿ':159};return map[ch]||63;}
  function hexText(value){let out='';for(const ch of String(value??''))out+=latinByte(ch).toString(16).padStart(2,'0');return `<${out}>`;}
  function money(v){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);}
  function date(v){if(!v)return '—';const d=new Date(String(v).length===10?`${v}T12:00:00`:v);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('pt-BR').format(d);}
  function dateTime(v=new Date()){const d=v instanceof Date?v:new Date(v);return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(d);}
  function cleanName(v){return String(v||'arquivo').replace(/[\\/:*?"<>|]/g,'-');}
  function hexRgb(value,fallback=[.07,.13,.20]){const m=String(value||'').match(/^#([0-9a-f]{6})$/i);if(!m)return fallback;const n=parseInt(m[1],16);return [((n>>16)&255)/255,((n>>8)&255)/255,(n&255)/255];}
  function rgb(value,fallback){return hexRgb(value,fallback).map(x=>Number(x.toFixed(3))).join(' ');}
  function wrap(text,maxChars){const raw=String(text??'').replace(/\r\n?/g,'\n');if(!raw.trim())return ['—'];const lines=[];for(const paragraph of raw.split('\n')){const words=paragraph.trim().split(/\s+/).filter(Boolean);if(!words.length){lines.push('');continue;}let line='';for(const w of words){if(!line){line=w;continue;}if((line+' '+w).length<=maxChars)line+=' '+w;else{lines.push(line);line=w;}}if(line)lines.push(line);}return lines.length?lines:['—'];}
  function pageSize(template){const page=template?.page||{},base=PAGE_SIZES[page.size]||PAGE_SIZES.A4;return page.orientation==='landscape'?{w:base.h,h:base.w}:{...base};}
  function pagePts(template){const p=pageSize(template);return {w:p.w*MM,h:p.h*MM,mm:p};}
  async function toJpeg(blob,max=1800,quality=.86){
    if(!(blob instanceof Blob))throw new Error('Imagem inválida.');
    const bmp=await createImageBitmap(blob);const scale=Math.min(1,max/Math.max(bmp.width,bmp.height));const w=Math.max(1,Math.round(bmp.width*scale)),h=Math.max(1,Math.round(bmp.height*scale));
    const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.drawImage(bmp,0,0,w,h);bmp.close?.();
    const out=await new Promise(r=>canvas.toBlob(r,'image/jpeg',quality));if(!out)throw new Error('Não foi possível converter a imagem.');return {bytes:new Uint8Array(await out.arrayBuffer()),width:w,height:h};
  }
  class Builder{
    constructor(){this.objects=[null];this.pages=[];this.pagesObj=this.reserve();this.catalogObj=this.reserve();this.fontRegular=this.add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>');this.fontBold=this.add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>');this.fontItalic=this.add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Oblique /Encoding /WinAnsiEncoding >>');}
    reserve(){this.objects.push(null);return this.objects.length-1;}
    add(value){const n=this.reserve();this.set(n,value);return n;}
    set(n,value){this.objects[n]=typeof value==='string'?ascii(value):value;}
    stream(bytes,dict=''){return this.add(concat([ascii(`<< /Length ${bytes.length}${dict?' '+dict:''} >>\nstream\n`),bytes,ascii('\nendstream')]));}
    image(bytes,w,h){return this.stream(bytes,`/Type /XObject /Subtype /Image /Width ${w} /Height ${h} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode`);}
    page(commands,images={},size={w:595.28,h:841.89}){const content=this.stream(ascii(commands));const names=Object.entries(images).map(([k,v])=>`/${k} ${v} 0 R`).join(' ');const resources=`<< /Font << /F1 ${this.fontRegular} 0 R /F2 ${this.fontBold} 0 R /F3 ${this.fontItalic} 0 R >>${names?` /XObject << ${names} >>`:''} >>`;const page=this.add(`<< /Type /Page /Parent ${this.pagesObj} 0 R /MediaBox [0 0 ${size.w} ${size.h}] /Resources ${resources} /Contents ${content} 0 R >>`);this.pages.push(page);return page;}
    finish(){this.set(this.pagesObj,`<< /Type /Pages /Kids [${this.pages.map(n=>`${n} 0 R`).join(' ')}] /Count ${this.pages.length} >>`);this.set(this.catalogObj,`<< /Type /Catalog /Pages ${this.pagesObj} 0 R >>`);const chunks=[ascii('%PDF-1.4\n%âãÏÓ\n')],offsets=[0];let offset=chunks[0].length;for(let i=1;i<this.objects.length;i++){offsets[i]=offset;const part=concat([ascii(`${i} 0 obj\n`),this.objects[i],ascii('\nendobj\n')]);chunks.push(part);offset+=part.length;}const xref=offset;let table=`xref\n0 ${this.objects.length}\n0000000000 65535 f \n`;for(let i=1;i<this.objects.length;i++)table+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;table+=`trailer\n<< /Size ${this.objects.length} /Root ${this.catalogObj} 0 R >>\nstartxref\n${xref}\n%%EOF`;chunks.push(ascii(table));return new Blob([concat(chunks)],{type:'application/pdf'});}
  }
  function textCmd(text,x,y,size=10,bold=false,color='0.07 0.13 0.20',italic=false){return `BT ${color} rg /${bold?'F2':italic?'F3':'F1'} ${size} Tf 1 0 0 1 ${x.toFixed(2)} ${y.toFixed(2)} Tm ${hexText(text)} Tj ET\n`;}
  function lineCmd(x1,y1,x2,y2,color='.82 .86 .9',width=.6){return `${color} RG ${width} w ${x1.toFixed(2)} ${y1.toFixed(2)} m ${x2.toFixed(2)} ${y2.toFixed(2)} l S\n`;}
  function rectCmd(x,y,w,h,{stroke='#c7d5e2',fill='',width=.6,opacity=1}={}){let cmd='';if(fill){cmd+=`${rgb(fill)} rg ${x.toFixed(2)} ${y.toFixed(2)} ${w.toFixed(2)} ${h.toFixed(2)} re f\n`;}if(stroke){cmd+=`${rgb(stroke)} RG ${width} w ${x.toFixed(2)} ${y.toFixed(2)} ${w.toFixed(2)} ${h.toFixed(2)} re S\n`;}return cmd;}
  function mixHexColor(start,end,t){const a=hexRgb(start,[.02,.10,.20]),b=hexRgb(end,[.08,.48,.76]),toByte=value=>Math.max(0,Math.min(255,Math.round(value*255))),hex=value=>toByte(value).toString(16).padStart(2,'0');return `#${hex(a[0]+(b[0]-a[0])*t)}${hex(a[1]+(b[1]-a[1])*t)}${hex(a[2]+(b[2]-a[2])*t)}`;}
  function gradientCmd(c,template){
    const p=pagePts(template),x=(Number(c.x)||0)*MM,y=p.h-((Number(c.y)||0)+(Number(c.height)||0))*MM,w=(Number(c.width)||0)*MM,h=(Number(c.height)||0)*MM,steps=72,start=c.startColor||'#031a35',end=c.endColor||'#137bc2';
    if(w<=0||h<=0)return '';
    let cmd='';
    if(c.gradientDirection==='horizontal'){
      const band=w/steps;
      for(let i=0;i<steps;i++)cmd+=rectCmd(x+i*band,y,band+.35,h,{stroke:'',fill:mixHexColor(start,end,i/(steps-1))});
    }else{
      const band=h/steps;
      for(let i=0;i<steps;i++)cmd+=rectCmd(x,y+h-(i+1)*band,w,band+.35,{stroke:'',fill:mixHexColor(start,end,i/(steps-1))});
    }
    return cmd;
  }
  function imageCmd(name,x,y,w,h,clip=null){const clipCmd=clip?`${clip.x.toFixed(2)} ${clip.y.toFixed(2)} ${clip.w.toFixed(2)} ${clip.h.toFixed(2)} re W n `:'';return `q ${clipCmd}${w.toFixed(2)} 0 0 ${h.toFixed(2)} ${x.toFixed(2)} ${y.toFixed(2)} cm /${name} Do Q\n`;}
  function basicTemplate(){return {id:'pdf-template-basic',name:'Projeto PDF 1',version:1,schemaVersion:1,page:{size:'A4',orientation:'portrait',margins:{top:10,right:10,bottom:10,left:10}},pages:[{id:'main',name:'Principal',components:[{id:'t1',type:'title',x:10,y:12,width:190,height:14,text:'ORDEM DE SERVIÇO — {{osv.codigo}}',fontSize:18,bold:true,color:'#092b52'},{id:'t2',type:'text',x:10,y:32,width:190,height:28,text:'{{empresa.nome}}\n{{empresa.telefone}} • {{empresa.email}}\n{{empresa.endereco}}',fontSize:9},{id:'t3',type:'text',x:10,y:66,width:190,height:64,text:'Cliente: {{cliente.nome}}\nTelefone: {{cliente.telefone}}\nEquipamento: {{equipamento.nome}}\nMarca / Modelo: {{equipamento.modelo}}\nProblema: {{osv.problema}}\nLaudo: {{osv.laudo}}',fontSize:9},{id:'it',type:'table-items',x:10,y:136,width:190,height:76,fontSize:8,overflow:'next-page'},{id:'tot',type:'text',x:110,y:218,width:90,height:20,text:'Desconto geral: {{osv.desconto}}\nTotal final: {{osv.total}}',fontSize:11,bold:true,align:'right'},{id:'pn',type:'page-number',x:150,y:286,width:50,height:6,text:'Página {{pagina.numero}} de {{pagina.total}}',fontSize:7,align:'right'}]},{id:'photos',name:'Fotos',dynamic:true,components:[{id:'pt',type:'title',x:10,y:10,width:190,height:12,text:'REGISTRO FOTOGRÁFICO — {{osv.codigo}}',fontSize:16,bold:true},{id:'pg',type:'photos-grid',x:10,y:28,width:190,height:245,columns:2,perPage:4,hideWhenEmpty:true},{id:'pp',type:'page-number',x:150,y:286,width:50,height:6,text:'Página {{pagina.numero}} de {{pagina.total}}',fontSize:7,align:'right'}]}]};}
  function resolveTemplate(order,ctx){if(ctx?.template?.pages)return ctx.template;try{const d=typeof data==='function'?data():null,s=d?.settings,templates=s?.pdfTemplates||[],id=order?.pdfTemplateId||s?.defaultPdfTemplateId;return templates.find(t=>t.id===id)||templates.find(t=>t.isDefault)||templates[0]||basicTemplate();}catch(_){return basicTemplate();}}
  function variableMap(order,ctx,pageNo=1,totalPages=1){const client=ctx.client||{},company=ctx.company||{},address=[company.address,company.number,company.neighborhood,company.city].filter(Boolean).join(', '),clientAddress=[client.address,client.number,client.neighborhood,client.city].filter(Boolean).join(', ');return {
    '{{empresa.nome}}':company.name||'Marco Iris Soluções em Tecnologia','{{empresa.cnpj}}':company.document||'','{{empresa.telefone}}':company.phone||'','{{empresa.email}}':company.email||'','{{empresa.endereco}}':address,
    '{{osv.codigo}}':order.id||'','{{osv.data}}':date(order.openedAt),'{{osv.status}}':order.status||'','{{osv.problema}}':order.reportedIssue||'','{{osv.laudo}}':order.technicalReport||'','{{osv.servicoRealizado}}':order.technicalReport||'','{{osv.observacoes}}':order.clientNotes||'','{{osv.desconto}}':money(order.discount),'{{osv.total}}':money(order.total),
    '{{cliente.nome}}':client.name||order.clientName||'','{{cliente.telefone}}':client.phone||'','{{cliente.email}}':client.email||'','{{cliente.endereco}}':clientAddress,
    '{{equipamento.nome}}':order.equipmentType||'','{{equipamento.marca}}':order.brandModel||'','{{equipamento.modelo}}':order.brandModel||'','{{equipamento.numeroSerie}}':order.serialNumber||'','{{equipamento.serie}}':order.serialNumber||'',
    '{{financeiro.subtotal}}':money((Number(order.total)||0)+(Number(order.discount)||0)),'{{financeiro.desconto}}':money(order.discount),'{{financeiro.total}}':money(order.total),
    '{{pix.favorecido}}':order.pixPayment?.enabled?(order.pixPayment.beneficiary||''):'','{{pix.documento}}':order.pixPayment?.enabled?(order.pixPayment.beneficiaryDocument||''):'','{{pix.banco}}':order.pixPayment?.enabled?(order.pixPayment.bankName||''):'','{{pix.chave}}':order.pixPayment?.enabled?(order.pixPayment.pixKey||''):'','{{pix.codigoCopiaCola}}':order.pixPayment?.enabled?(order.pixPayment.copyPasteCode||order.pixPayment.pixKey||''):'','{{pix.qrCode}}':order.pixPayment?.enabled?'QR Code Pix':'',
    '{{pagina.numero}}':String(pageNo),'{{pagina.total}}':String(totalPages),'{{sistema.dataGeracao}}':dateTime(new Date())
  };}
  function resolveText(text,map){return Object.entries(map).reduce((out,[k,v])=>out.split(k).join(v),String(text||''));}
  function entriesFor(type,ctx){const all=ctx.items||[];if(type==='table-products')return all.filter(x=>String(x.type||'').toLowerCase().includes('produto'));if(type==='table-services')return all.filter(x=>String(x.type||'').toLowerCase().includes('serv'));if(type==='table-payments')return ctx.payments||[];return all;}
  function rowsFor(type,ctx){const itemName=it=>it.description||ctx.itemName?.(it)||[it.type,it.productId||it.serviceId||it.supplyId].filter(Boolean).join(' ');if(type==='table-payments')return (ctx.payments||[]).map(p=>{const status=globalThis.MarcoFinanceStatus?.effectiveStatus?.(p)||p.status||'Em aberto';return {a:p.paymentMethod||'—',b:p.paymentDate?`Pago em ${date(p.paymentDate)}`:p.dueDate?`${status} · ${date(p.dueDate)}`:status,c:money(p.grossValue||p.value)};});return entriesFor(type,ctx).map(it=>({a:`${Number(it.quantity)||0} × ${itemName(it)}`,b:money(it.unitPrice),c:money(Number(it.subtotal)||((Number(it.quantity)||0)*(Number(it.unitPrice)||0)))}));}
  function textMetrics(c,template,map){const p=pagePts(template),w=c.width*MM,size=Number(c.fontSize)||10,lineHeight=size*(Number(c.lineHeight)||1.28),maxChars=Math.max(4,Math.floor(w/(size*.52))),lines=wrap(resolveText(c.text||c.label||'',map),maxChars),maxLines=c.height?Math.max(1,Math.floor((c.height*MM)/lineHeight)):lines.length;return {p,w,size,lineHeight,lines,maxLines};}
  function tableMetrics(c,ctx){const rows=rowsFor(c.type,ctx),font=Number(c.fontSize)||8,rowH=Math.max(14,font*1.45),boxH=(Number(c.height)||50)*MM,capacity=Math.max(1,Math.floor(boxH/rowH)-1);return {rows,font,rowH,capacity};}
  function hasDynamicChunk(index,tables,overflowTexts,template,ctx,map){for(const c of tables){const {rows,capacity}=tableMetrics(c,ctx);if(rows.slice(index*capacity,(index+1)*capacity).length)return true;}for(const c of overflowTexts){const resolved=resolveText(c.text||c.label||'',map);if(!resolved.trim()&&c.hideWhenEmpty)continue;const metrics=textMetrics(c,template,map);if(metrics.lines.slice(index*metrics.maxLines,(index+1)*metrics.maxLines).length)return true;}return false;}
  function planPages(template,order,ctx){const plans=[],planningMap=variableMap(order,ctx,1,1);for(const page of template.pages||[]){const components=(page.components||[]).filter(c=>!String(c?.type||'').startsWith('pix-')),photoComp=components.find(c=>c.type==='photos-grid'),tables=components.filter(c=>String(c.type).startsWith('table-')),overflowTexts=components.filter(c=>c.overflow==='next-page'&&['text','title','subtitle','field','signature'].includes(c.type));if(photoComp){const photos=order.photos||[];if(!photos.length&&photoComp.hideWhenEmpty)continue;const per=Math.max(1,Number(photoComp.perPage)||4),chunks=[];for(let i=0;i<Math.max(1,photos.length);i+=per)chunks.push(photos.slice(i,i+per));if(!chunks.length)chunks.push([]);chunks.forEach((chunk,index)=>plans.push({page,photoChunk:chunk,photoIndex:index,tableChunkIndex:0,textChunkIndex:index,continuation:index>0}));continue;}let count=1;for(const c of tables){const {rows,capacity}=tableMetrics(c,ctx);count=Math.max(count,Math.ceil(rows.length/capacity)||1);}for(const c of overflowTexts){const resolved=resolveText(c.text||c.label||'',planningMap);if(!resolved.trim()&&c.hideWhenEmpty)continue;const metrics=textMetrics(c,template,planningMap);count=Math.max(count,Math.ceil(metrics.lines.length/metrics.maxLines)||1);}for(let i=0;i<count;i++){if(i>0&&!hasDynamicChunk(i,tables,overflowTexts,template,ctx,planningMap))continue;plans.push({page,photoChunk:null,tableChunkIndex:i,textChunkIndex:i,continuation:i>0});}}return plans.length?plans:[{page:basicTemplate().pages[0],tableChunkIndex:0,textChunkIndex:0,continuation:false}];}
  function textBoxCmd(text,c,template,map,chunkIndex=0){const metrics=textMetrics({...c,text},template,map),{p,w,size,lineHeight,maxLines}=metrics,lines=c.overflow==='next-page'?metrics.lines.slice(chunkIndex*maxLines,(chunkIndex+1)*maxLines):metrics.lines.slice(0,maxLines);if(!lines.length)return '';const x=c.x*MM,yTop=p.h-c.y*MM,color=rgb(c.color),align=c.align||'left';let cmd='';if(c.backgroundColor)cmd+=rectCmd(x,p.h-(c.y+c.height)*MM,w,c.height*MM,{stroke:'',fill:c.backgroundColor});for(let i=0;i<lines.length;i++){const line=lines[i],approx=line.length*size*.52;let tx=x;if(align==='center')tx=x+(w-approx)/2;else if(align==='right')tx=x+w-approx;const ty=yTop-size-i*lineHeight;cmd+=textCmd(line,Math.max(x,tx),ty,size,!!c.bold,color,!!c.italic);}if(c.underline){const y=yTop-size-2;cmd+=lineCmd(x,y,x+w,y,color,.5);}return cmd;}
  function tableCmd(c,template,ctx,chunkIndex,map){const {rows,font,rowH,capacity}=tableMetrics(c,ctx),slice=rows.slice(chunkIndex*capacity,(chunkIndex+1)*capacity);if(!slice.length&&(chunkIndex>0||c.hideWhenEmpty))return '';const p=pagePts(template),x=c.x*MM,yTop=p.h-c.y*MM,w=c.width*MM,col1=w*.62,col2=w*.18,col3=w*.20;let cmd=rectCmd(x,yTop-rowH,w,rowH,{fill:'#e8f1f8',stroke:'#9db7cd'});const title=c.type==='table-payments'?'PAGAMENTOS':c.type==='table-products'?'Produtos':c.type==='table-services'?'Serviços':'Itens e serviços';cmd+=textCmd(title,x+4,yTop-rowH+4,font,true,rgb('#092b52'));cmd+=textCmd(c.type==='table-payments'?'Status':'Unitário',x+col1+3,yTop-rowH+4,font,true,rgb('#092b52'));cmd+=textCmd('Total',x+col1+col2+3,yTop-rowH+4,font,true,rgb('#092b52'));let y=yTop-rowH;for(const row of slice){y-=rowH;cmd+=rectCmd(x,y,w,rowH,{stroke:'#cad6e1',fill:''});cmd+=lineCmd(x+col1,y,x+col1,y+rowH,rgb('#cad6e1'));cmd+=lineCmd(x+col1+col2,y,x+col1+col2,y+rowH,rgb('#cad6e1'));const a=wrap(row.a,Math.max(8,Math.floor(col1/(font*.52)))).slice(0,2);a.forEach((line,i)=>{cmd+=textCmd(line,x+4,y+rowH-font-2-i*(font+1),font,false,rgb('#25394e'));});cmd+=textCmd(row.b,x+col1+3,y+rowH-font-3,font,false,rgb('#25394e'));cmd+=textCmd(row.c,x+col1+col2+3,y+rowH-font-3,font,!!c.bold,rgb('#25394e'));}return cmd;}
  async function resolveAssetBlob(c){try{if(c.assetLocalKey&&globalThis.MarcoStorage?.getMedia){const rec=await MarcoStorage.getMedia(c.assetLocalKey);if(rec?.blob)return rec.blob;}if(c.assetUrl){const response=await fetch(c.assetUrl);if(response.ok)return await response.blob();}}catch(error){console.warn?.('Imagem opcional do PDF indisponível:',c.assetUrl||c.assetLocalKey,error?.message||error);}return null;}
  function imageQuality(template){const quality=template?.quality||'standard';return quality==='optimized'?{max:1200,jpeg:.74}:quality==='high'?{max:2400,jpeg:.94}:{max:1600,jpeg:.86};}
  async function renderImageComponent(c,b,template,images,imageSeq){const blob=await resolveAssetBlob(c);if(!blob)return {cmd:'',imageSeq};try{const quality=imageQuality(template),img=await toJpeg(blob,quality.max,quality.jpeg),obj=b.image(img.bytes,img.width,img.height),name=`Img${imageSeq++}`,p=pagePts(template),box={x:c.x*MM,y:p.h-(c.y+c.height)*MM,w:c.width*MM,h:c.height*MM};const cover=c.fit==='cover',scale=cover?Math.max(box.w/img.width,box.h/img.height):Math.min(box.w/img.width,box.h/img.height),w=img.width*scale,h=img.height*scale,x=box.x+(box.w-w)/2,y=box.y+(box.h-h)/2;images[name]=obj;return {cmd:imageCmd(name,x,y,w,h,cover?box:null),imageSeq};}catch(error){console.warn?.('Imagem opcional do PDF ignorada por falha de leitura:',c.assetName||c.assetUrl||c.assetLocalKey,error?.message||error);return {cmd:'',imageSeq};}}
  async function renderPixQrComponent(c,b,template,order,images,imageSeq){
    const code=String(order?.pixPayment?.copyPasteCode||order?.pixPayment?.pixKey||'').trim();if(!order?.pixPayment?.enabled||!code||!globalThis.MarcoQr)return {cmd:'',imageSeq};
    try{const blob=await MarcoQr.toBlob(code,{size:900,margin:4,level:'Q'}),img=await toJpeg(blob,1200,.96),obj=b.image(img.bytes,img.width,img.height),name=`PixQr${imageSeq++}`,p=pagePts(template),box={x:c.x*MM,y:p.h-(c.y+c.height)*MM,w:c.width*MM,h:c.height*MM},side=Math.min(box.w,box.h),x=box.x+(box.w-side)/2,y=box.y+(box.h-side)/2;images[name]=obj;let cmd=rectCmd(box.x,box.y,box.w,box.h,{stroke:'#c7d5e2',fill:'#ffffff',width:.5});cmd+=imageCmd(name,x,y,side,side);return {cmd,imageSeq};}catch(error){console.warn?.('QR Code Pix não pôde ser renderizado:',error?.message||error);return {cmd:'',imageSeq};}
  }
  async function photosGrid(c,b,template,photos,ctx,images,imageSeq,map){if(!photos.length&&c.hideWhenEmpty)return {cmd:'',imageSeq};const p=pagePts(template),columns=Math.max(1,Math.min(3,Number(c.columns)||2)),gap=4*MM,x=c.x*MM,yTop=p.h-c.y*MM,w=c.width*MM,h=c.height*MM,rows=Math.max(1,Math.ceil(Math.max(1,photos.length)/columns)),cellW=(w-gap*(columns-1))/columns,cellH=(h-gap*(rows-1))/rows;let cmd='';for(let i=0;i<photos.length;i++){const meta=photos[i];try{const blob=await ctx.getPhotoBlob?.(meta);if(!blob)continue;const quality=imageQuality(template),img=await toJpeg(blob,quality.max,quality.jpeg),obj=b.image(img.bytes,img.width,img.height),name=`Photo${imageSeq++}`,col=i%columns,row=Math.floor(i/columns),cellX=x+col*(cellW+gap),cellY=yTop-(row+1)*cellH-row*gap,caption=c.showCaption!==false?14:0,fitH=cellH-caption,scale=Math.min(cellW/img.width,fitH/img.height),iw=img.width*scale,ih=img.height*scale,ix=cellX+(cellW-iw)/2,iy=cellY+caption+(fitH-ih)/2;images[name]=obj;cmd+=rectCmd(cellX,cellY,cellW,cellH,{stroke:'#c7d4df'});cmd+=imageCmd(name,ix,iy,iw,ih);if(c.showCaption!==false)cmd+=textCmd(meta.fileName||`Foto ${i+1}`,cellX+3,cellY+4,7,false,rgb('#637487'));}catch(e){console.warn('Foto ignorada no PDF:',e);}}return {cmd,imageSeq};}
  async function renderPlan(plan,index,total,b,template,order,ctx){
    const p=pagePts(template),map=variableMap(order,ctx,index+1,total),images={};
    const sorted=[...(plan.page.components||[])].sort((a,b)=>(a.zIndex||0)-(b.zIndex||0));
    const overflowTexts=sorted.filter(c=>c.overflow==='next-page'&&['text','title','subtitle','field','signature'].includes(c.type));
    const tables=sorted.filter(c=>String(c.type||'').startsWith('table-'));
    const chunkIndex=plan.textChunkIndex||0;
    const hasTextChunk=overflowTexts.some(c=>{
      const metrics=textMetrics(c,template,map);
      return metrics.lines.slice(chunkIndex*metrics.maxLines,(chunkIndex+1)*metrics.maxLines).length>0;
    });
    const minDynamicY=Math.min(...[...overflowTexts,...tables].map(c=>Number(c.y)||0),Infinity);
    const minTableY=Math.min(...tables.map(c=>Number(c.y)||0),Infinity);
    let cmd='',imageSeq=1;
    for(const original of sorted){
      if(original.hidden||String(original.type||'').startsWith('pix-'))continue;
      if(plan.continuation&&!String(original.type||'').startsWith('table-')&&original.type!=='photos-grid'&&original.overflow!=='next-page'&&!original.repeatOnEveryPage&&!['page-number','generation-date','logo'].includes(original.type)&&Number(original.y)>45)continue;
      let c=original;
      if(plan.continuation&&(original.overflow==='next-page'||String(original.type||'').startsWith('table-'))){
        c={...original};
        if(String(original.type||'').startsWith('table-')&&!hasTextChunk&&Number.isFinite(minTableY))c.y=(Number(original.y)||0)+(55-minTableY);
        else if(Number.isFinite(minDynamicY))c.y=(Number(original.y)||0)+(55-minDynamicY);
      }
      if(['text','title','subtitle','field','signature','page-number','generation-date'].includes(c.type)){
        const resolved=resolveText(c.text||c.label,map);if(!resolved.trim()&&c.hideWhenEmpty)continue;
        cmd+=textBoxCmd(resolved,c,template,map,plan.textChunkIndex||0);continue;
      }
      if(c.type==='line'){const x=c.x*MM,y=p.h-c.y*MM;cmd+=lineCmd(x,y,x+c.width*MM,y,rgb(c.color||'#2d72b8'),Math.max(.4,Number(c.strokeWidth)||1));continue;}
      if(c.type==='gradient'){cmd+=gradientCmd(c,template);continue;}
      if(c.type==='rect'){const x=c.x*MM,y=p.h-(c.y+c.height)*MM;cmd+=rectCmd(x,y,c.width*MM,c.height*MM,{stroke:c.color||'#2d72b8',fill:c.backgroundColor||''});continue;}
      if(c.type==='logo'||c.type==='image'){const out=await renderImageComponent(c,b,template,images,imageSeq);cmd+=out.cmd;imageSeq=out.imageSeq;continue;}
      if(c.type==='pix-qr'){const out=await renderPixQrComponent(c,b,template,order,images,imageSeq);cmd+=out.cmd;imageSeq=out.imageSeq;continue;}
      if(String(c.type).startsWith('table-')){cmd+=tableCmd(c,template,ctx,plan.tableChunkIndex||0,map);continue;}
      if(c.type==='photos-grid'){const out=await photosGrid(c,b,template,plan.photoChunk||[],ctx,images,imageSeq,map);cmd+=out.cmd;imageSeq=out.imageSeq;continue;}
    }
    b.page(cmd,images,{w:p.w,h:p.h});
  }
  async function generateVisual(order,ctx,template){const b=new Builder(),plans=planPages(template,order,ctx);for(let i=0;i<plans.length;i++)await renderPlan(plans[i],i,plans.length,b,template,order,ctx);const stamp=new Date().toLocaleString('sv-SE',{hour12:false}).replace(' ','_').replace(/:/g,'-');return {blob:b.finish(),fileName:`${cleanName(order.id)}_${stamp}.pdf`,templateId:template.id||'',templateVersion:template.version||1,pageCount:plans.length};}
  async function generate(order,ctx={}){const template=resolveTemplate(order,ctx);return await generateVisual(order,ctx,template);}
  window.MarcoPdf={generate,resolveTemplate,basicTemplate};
})();
